import { useEffect, useState } from "react";
import Head from "next/head";
import { Spinner, View } from "vcc-ui";
import { CarItem } from "@/types/Car.model";
import home from "../styles/home.module.scss";
import cars from "../public/api/cars.json";
import Filter from "../src/components/Filter";
import Slider from "../src/components/Slider/index";
import CarCard from "../src/components/CarCard";

interface Props {
  carsList?: CarItem[];
}
const Home = (props: Props) => {
  const { carsList = [] } = props;
  const [carTypes, setCarTypes] = useState<string[]>([""]);
  const [filteredCarList, setFilteredCarList] = useState<CarItem[]>([]);
  useEffect(() => {
    const carBodyTypes = carsList.map((car: CarItem) => car.bodyType);
    setCarTypes([...new Set(carBodyTypes)]);
    setFilteredCarList(carsList);
    console.log(filteredCarList);
  }, []);
  const onFilterValueChange = (value: string) => {
    if (value === "Show All") {
      setFilteredCarList(carsList);
    } else {
      setFilteredCarList(
        carsList.filter((car: CarItem) => car.bodyType === value)
      );
    }
  };
  return (
    <div className={home.container}>
      <Head>
        <title>Cars Gallery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {carsList.length ? (
        <main className={home.main}>
          <Filter
            carTypes={carTypes}
            onValueChange={(value: string) => onFilterValueChange(value)}
          />
          <Slider>
            {filteredCarList.map((carItem: CarItem) => {
              return (
                <CarCard showLinks={true} carItem={carItem} key={carItem.id} />
              );
            })}
          </Slider>
        </main>
      ) : (
        <View>
          <Spinner size={48}></Spinner>
        </View>
      )}

      <footer className={home.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {"Sherif "}
          <span className={home.logo}></span>
        </a>
      </footer>
    </div>
  );
};
export async function getServerSideProps() {
  return {
    props: {
      carsList: cars,
    },
  };
}
export default Home;
